### ISSUE TITLE
no module named 'petrel_client' and ImportError:cannot import name 'DEPLOY_REGISTRY' 

### ISSUE THREAD

**Issue by Huangszz** [ModelTC/United-Perception#25]
Hi, 
    no module named 'petrel_client'
    ImportError:cannot import name 'DEPLOY_REGISTRY' 

Can  you tell me how to improve this problem?

**Comment by Huangszz** [comment]
Hi,
no module named 'petrel_client'
ImportError:cannot import name 'DEPLOY_REGISTRY'

Can you tell me how to improve this problem?

**Comment by yqyao** [comment]
Sorry for the late reply， we have fixed this bug by https://github.com/ModelTC/United-Perception/commit/bf242b80467f3abd337e02c9a0fd9c68e1644735 . @Huangszz

**Comment by Huangszz** [comment]
Thank you for your kind reply. And can you tell me how should I get start of the EFL with yolox_medium?
  I have download the weight for yolox_medium, I use the command as follows:
    ./easy_setup.sh
    ./scripts/dist_dist.sh 2 configs/det/efl/efl_yolox_medium.yaml
  Is this right?  But then I got error as follows:
   1. ModuleNotFoundError:No module named 'up.extensions._C'
   2. ./scripts/dist_test.sh：行 13：--launch=pytorch：未找到命令

   Can you give me some advices if possible? Thank you very much!

**Comment by yqyao** [comment]
[maybe you need ](https://eod.readthedocs.io/en/latest/Chinese/installation/index.html), question1 is compilation error。

**Comment by Huangszz** [comment]
> [maybe you need ](https://eod.readthedocs.io/en/latest/Chinese/installation/index.html), question1 is compilation error。

I have tried many times according to the [document](https://eod.readthedocs.io/en/latest/Chinese/installation/index.html), but it still doesn't work. Could you give me a detailed readme for EFL experiment?

**Comment by Huangszz** [comment]
> [maybe you need ](https://eod.readthedocs.io/en/latest/Chinese/installation/index.html), question1 is compilation error。

I have tried many times according to the [document](https://eod.readthedocs.io/en/latest/Chinese/installation/index.html), but it still doesn't work. Could you give me a detailed readme for EFL experiment?
